// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {menu} from '../models';

export function Greet(arg1:app.Person):Promise<string>;

export function Menu():Promise<menu.Menu>;
